[project]
name = "pyjot-cli"
version = "0.1.0"
description = "A CLI To-Do application written in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "typer>=0.16.1",
]
